- platform: nmap_tracker
  track_new_devices: false
  consider_home: 600
  interval_seconds: 2
  scan_options: "-F --host-timeout 1s"
  hosts:
    - 192.168.1.143 # justin
#    - 192.168.1.149 # celeste
#- platform: owntracks
