version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - aws ssm get-parameter --name home-assistant-secrets| jq -r .Parameter.Value > secrets.yaml
      - pip install -r requirements.txt
  build:
    commands:
      - hass --script check_config -c $PWD
