homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: Australia/Brisbane
  customize: !include customize.yaml

http:
  api_password: G20REbaPlav02w3TBdge
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: hass.dray.id.au

recorder:
  purge_interval: 2
  purge_keep_days: 14

#discovery:
updater:
frontend:
config:
conversation:
history:
logbook:
map:
sun:

#tts:
#  - platform: google

#logger:
#  default: info
#  logs:
#    aiounifi: debug
#    homeassistant.components.unifi: debug
#    homeassistant.components.switch.unifi: debug


panel_iframe:
  nodered_flows:
    title: 'Node-RED Flows'
    url: 'https://node-red.dray.id.au'
    icon: mdi:nodejs

ifttt:
  key: !secret ifttt_key

input_boolean:
  automations:
    name: Automations
    initial: on
    icon: mdi:house 

#zha: !include misc/zha.yaml
xiaomi_aqara: !include misc/xiaomi_aqara.yaml
influxdb: !include misc/influxdb.yaml
alexa: !include misc/alexa.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include_dir_list sensors/
mqtt: !include misc/mqtt.yaml
switch: !include_dir_list switches/
light: !include_dir_list lights/
#automation: !include_dir_merge_list automations/
automation: !include automations.yaml
notify: !include_dir_list notify/
hue: !include hue.yaml
cover: !include_dir_list covers/
