homeassistant:
    name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    elevation: !secret elevation_home
    unit_system: metric
    time_zone: Australia/Brisbane
    customize:
        script.wake_ironwood:
            emulated_hue: true
            emulated_hue_name: Ironwood
        media_player.samsung_tv_remote:
            emulated_hue: true
            emulated_hue_name: TV
        group.all_lights:
            emulated_hue: true

emulated_hue:
    expose_by_default: true
    exposed_domains:
        - light

ifttt:
    key: !secret ifttt_key

frontend:
conversation:
history:
logbook:
sun:
http:
    api_password: !secret api_password
recorder:
    purge_days: 28
logger:
    default: warning
    logs:
        homeassistant.components.device_tracker.mqtt: debug


mqtt: !include misc/mqtt.yaml
device_tracker: !include misc/device_trackers.yaml
#shell_command: !include misc/shell_commands.yaml
shell_command:
  wake_ironwood: wol 54:04:a6:18:63:6d
media_player: !include misc/media_players.yaml
sensor: !include_dir_list sensors/
script: !include_dir_merge_named scripts/
light: !include_dir_list lights/
automation: !include_dir_list automations/
zone: !include_dir_list zones/
notify: !include misc/notifiers.yaml
