homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: Australia/Brisbane
  customize: !include customize.yaml

emulated_hue:
  expose_by_default: true
  listen_port: 80
  exposed_domains:
    - light
    - scene

ifttt:
  key: !secret ifttt_key

frontend:
conversation:
history:
logbook:
sun:
http:
  api_password: !secret api_password
recorder:
  purge_interval: 2
  purge_keep_days: 14
logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.mqtt: debug

xiaomi_aqara: !include misc/xiaomi_aqara.yaml

#mqtt: !include misc/mqtt.yaml
device_tracker: !include misc/device_trackers.yaml
shell_command: !include misc/shell_commands.yaml
media_player: !include misc/media_players.yaml
sensor: !include_dir_list sensors/
script: !include_dir_merge_named scripts/
switch: !include_dir_list switches/
light: !include_dir_list lights/
automation: !include_dir_merge_list automations/
zone: !include_dir_list zones/
notify: !include misc/notifiers.yaml
scene: !include_dir_list scenes/
