#!/bin/bash

export AWS_REGION=ap-southeast-2

usage() {
	cat <<-EOF
		Usage: ./$0 push|pull
	EOF
}

pull() {
	aws ssm get-parameter --name home-assistant-secrets | jq -r .Parameter.Value >secrets.yaml
}

push() {
	aws ssm put-parameter --name home-assistant-secrets --value "$(cat secrets.yaml)" --type String --overwrite
}

case $1 in
pull) pull ;;
push) push ;;
*) usage ;;
esac
