version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - aws ssm get-parameter --name home-assistant-secrets| jq -r .Parameter.Value > secrets.yaml
      - docker pull homeassistant/home-assistant
  build:
    commands:
      - docker run -v $PWD:/config homeassistant/home-assistant python -m homeassistant --script check_config -c /config
