alias: Button Test
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: binary_sensor.switch_158d0001aaadad
    from: "off"
    to: "on"
action:
  - service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: 34:CE:00:91:DA:9C
      ringtone_id: 10
      ringtone_vol: 30
