alias: Motion Test
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor_158d0001b156ed
    from: "off"
    to: "on"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.all_devices
      state: home
action:
  - service: light.turn_on
    data:
      entity_id:
        - light.gateway_light_34ce0091da9c
      brightness: 255
