alias: Sunset
initial_state: True
hide_entity: False
trigger:
    platform: sun
    event: sunset
    offset: "-0:15:00"
condition:
    - condition: state
      entity_id: group.all_devices
      state: "home"
action:
    - service: light.turn_on
      data:
          entity_id:
              - light.lounge
          brightness: 200
          color_temp: 154
          rgb_color: [255,255,255]
