alias: Sunset
initial_state: True
hide_entity: False
trigger:
  platform: sun
  event: sunset
  offset: "-01:00:00"
condition:
  condition: state
  entity_id: group.all_devices
  state: "home"
action:
  service: light.turn_on
  data:
    entity_id:
      - light.lounge
    brightness_pct: 100
    color_temp: 427
