- alias: Turn on stair lights (Bright)
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001b156ed
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "7:00:00"
        before: "22:59:59"
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.illumination_34ce0091da9c # This is the hub sensor, it seems to only update on other state changes, so is mostly useless. Try using the new motion sensor illumination value instead once it's set up
            below: 135
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.staircase
          - light.upstairs
        brightness_pct: 100
        color_temp: 339

- alias: Turn on stair lights (Dim)
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001b156ed
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "23:00:00"
        before: "6:59:59"
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.illumination_34ce0091da9c
            below: 135
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.staircase
          - light.upstairs
        brightness_pct: 40
        color_temp: 339

- alias: Turn off stair lights
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001b156ed
      to: "off"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.staircase
          - light.upstairs
