- alias: Turn on stair lights (Bright)
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001b156ed
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: time
        after: "10:00:00"
        before: "23:59:59"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.staircase
          - light.upstairs
        brightness_pct: 100
        color_temp: 339

- alias: Turn on stair lights (Dim)
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001b156ed
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: time
        after: "00:00:00"
        before: "10:00:00"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.staircase
          - light.upstairs
        brightness_pct: 40
        color_temp: 339

- alias: Turn off stair lights
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001b156ed
      to: "off"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.staircase
          - light.upstairs
